#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Aninda Sundar Howlader (GRU953)
"""Copy the generated design tokens from the brand kit into the two delivery trees.

WHY THIS EXISTS
---------------
The brand kit generates the tokens (04_colour/engine.py). The plugin ships a copy so a
skill works with nothing else installed, and the design system ships a copy so a card
renders on its own. Three copies of one file is three chances to disagree, and they did:
an audit found the plugin's tokens.json carrying two roles the design system's did not,
so `asset.py tokens --format json` and `build.py` published different metadata for the
same stylesheet.

One copy is authoritative. This script makes the other two match it, and `--check`
refuses to pass if they do not — which is what runs before anything is packaged.

    python3 sync-tokens.py            # copy kit -> plugin, design system
    python3 sync-tokens.py --check    # compare only; non-zero exit if any copy is stale
"""
import argparse
import hashlib
import pathlib
import shutil
import sys

HERE = pathlib.Path(__file__).resolve().parent
KIT = HERE / "brand-kit" / "08_guidebook" / "assets"
TARGETS = [
    HERE / "plugin" / "gru953" / "skills" / "gru953-branding" / "assets",
    HERE / "design-system" / "tokens",
]
FILES = ["tokens.css", "tokens.json", "typography.css", "layout.css"]

# components.css is authored in the design system, not generated by the brand kit, but the
# plugin ships a copy so /gru953:design can build a real screen. Same problem, same answer.
EXTRA = [(HERE / "design-system" / "src" / "components.css",
          HERE / "plugin" / "gru953" / "skills" / "gru953-branding" / "assets"
          / "components.css")]


def digest(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12] if p.exists() else "MISSING"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="compare only, write nothing, exit non-zero if a copy is stale")
    a = ap.parse_args()

    if not KIT.is_dir():
        sys.exit(f"the brand kit's generated assets are not at {KIT} — run "
                 f"04_colour/engine.py first")
    missing = [f for f in FILES if not (KIT / f).exists()]
    if missing:
        sys.exit(f"the brand kit has not generated {', '.join(missing)} — run engine.py")

    stale, copied = [], []
    for target in TARGETS:
        if not target.is_dir():
            sys.exit(f"{target} does not exist")
        for f in FILES:
            src, dst = KIT / f, target / f
            if digest(src) == digest(dst):
                continue
            rel = dst.relative_to(HERE)
            if a.check:
                stale.append(f"{rel}  ({digest(dst)} != kit {digest(src)})")
            else:
                shutil.copyfile(src, dst)
                copied.append(str(rel))

    for src, dst in EXTRA:
        if digest(src) == digest(dst):
            continue
        if a.check:
            stale.append(f"{dst.relative_to(HERE)}  ({digest(dst)} != {digest(src)})")
        else:
            shutil.copyfile(src, dst)
            copied.append(str(dst.relative_to(HERE)))

    if a.check:
        if stale:
            print("STALE — these copies do not match the brand kit:")
            for s in stale:
                print(f"  ✗ {s}")
            print("\nRun `python3 sync-tokens.py` to bring them into line.")
            return 1
        print(f"in step — {len(FILES)} generated files x {len(TARGETS)} trees, "
              f"plus {len(EXTRA)} authored file(s)")
        return 0

    if copied:
        for c in copied:
            print(f"  updated  {c}")
    print(f"{len(copied)} file(s) updated; "
          f"{len(FILES) * len(TARGETS) + len(EXTRA) - len(copied)} already in step")
    return 0


if __name__ == "__main__":
    sys.exit(main())
